# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b96adf153a3c16710fbb8199fd89c0b816941ef1365c7069095e130085629e8e69d283e24d98724cd76e52f7d96fe2d97ae95c0b1298b57bc1ea52a9b901d357

test:
  secret_key_base: 58018b739b05f42d6867da26b1c8df30bd3ff4ec52b7f8930b411ab59bb5f9a1c8d937aec2edf1783d7a716dc2aa0241ec97a0207a9c43beb0eb45677977f80c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
